name: PR Check

on:
  pull_request:
    branches: [ main ]

jobs:
  build-extension:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install dependencies
      working-directory: Extension
      run: npm install && chmod +x node_modules/.bin/*

    - name: Compile TypeScript
      working-directory: Extension
      run: npx tsc -p ./

    - name: Package extension
      working-directory: Extension
      run: |
        BUILD_VERSION="1.0.$(date +%Y%m%d%H%M%S)"
        jq --arg v "$BUILD_VERSION" '.version = $v' package.json > package.json.tmp
        mv package.json.tmp package.json
        npx vsce package --out bitswan-extension.vsix
